worker_processes auto;
# Configuração do Nginx para o Gestor App
events {
    worker_connections 1024;
}

# Configuração do Servidor Nginx para o Gestor App
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Aumenta o limite de upload para 1 Megabytes ---
    client_max_body_size 1M;

    # Configuração de Compressão (Gzip) para carregar o react mais rápido
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    server {
        listen 80;
        # Dominio da sua aplicação, substitua pelo seu domínio real
        server_name seu.domínio.com;

        # Redireciona HTTP para HTTPS
        return 301 https://$host$request_uri;
    }
        # Configuração do Servidor Nginx para o Gestor App
        server {
        listen 443 ssl;
        # Dominio da sua aplicação, substitua pelo seu domínio real
        server_name seu.domínio.com;

        # Configuração do SSL
        ssl_certificate     /etc/nginx/ssl/exemplo.pem;
        ssl_certificate_key /etc/nginx/ssl/exemplo.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Rota para o Frontend React Native
        location / {
            proxy_pass http://Gestor:8300;
            # Configurações de cabeçalho para o proxy
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Rota para a API .NET
        location /api/ {
            proxy_pass http://Gestor:8092;
            # Configurações de cabeçalhos para manter informações do cliente
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            # Desativa o buffering para evitar problemas de timeout
            proxy_buffering off;
            # Configurações de timeout para evitar erros de gateway
            proxy_connect_timeout 90;
            proxy_send_timeout 90;
            proxy_read_timeout 90;
        }
    }
}